from decimal import Decimal

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def ts_fields(extra):
    return [
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        *extra,
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
    ]


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=ts_fields([
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("is_active", models.BooleanField(default=True)),
            ]),
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=ts_fields([
                ("name", models.CharField(max_length=40)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="academic_years", to="backend.school")),
            ]),
            options={"ordering": ["-start_date"], "unique_together": {("school", "name")}},
        ),
        migrations.CreateModel(
            name="Branch",
            fields=ts_fields([
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=30)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="branches", to="backend.school")),
            ]),
            options={
                "ordering": ["school", "name"],
                "unique_together": {("school", "code"), ("school", "name")},
            },
        ),
        migrations.CreateModel(
            name="GradeLevel",
            fields=ts_fields([
                ("name", models.CharField(max_length=60)),
                ("code", models.CharField(max_length=20)),
                ("order", models.PositiveSmallIntegerField(validators=[MinValueValidator(1)])),
                ("is_active", models.BooleanField(default=True)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="grade_levels", to="backend.school")),
            ]),
            options={
                "ordering": ["school", "order"],
                "unique_together": {("school", "code"), ("school", "order")},
            },
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=ts_fields([
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="guardians", to="backend.school")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="guardian_profiles", to=settings.AUTH_USER_MODEL)),
            ]),
            options={"ordering": ["school", "last_name", "first_name"]},
        ),
        migrations.CreateModel(
            name="Student",
            fields=ts_fields([
                ("student_number", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(choices=[("male", "Male"), ("female", "Female"), ("other", "Other"), ("unspecified", "Unspecified")], default="unspecified", max_length=20)),
                ("admission_date", models.DateField()),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive"), ("graduated", "Graduated"), ("withdrawn", "Withdrawn")], default="active", max_length=20)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="students", to="backend.school")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="student_profiles", to=settings.AUTH_USER_MODEL)),
            ]),
            options={"ordering": ["school", "student_number"], "unique_together": {("school", "student_number")}},
        ),
        migrations.CreateModel(
            name="Subject",
            fields=ts_fields([
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subjects", to="backend.school")),
            ]),
            options={"ordering": ["school", "name"], "unique_together": {("school", "code"), ("school", "name")}},
        ),
        migrations.CreateModel(
            name="Term",
            fields=ts_fields([
                ("name", models.CharField(max_length=50)),
                ("order", models.PositiveSmallIntegerField(validators=[MinValueValidator(1)])),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("academic_year", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="terms", to="backend.academicyear")),
            ]),
            options={"ordering": ["academic_year", "order"], "unique_together": {("academic_year", "name"), ("academic_year", "order")}},
        ),
        migrations.CreateModel(
            name="Room",
            fields=ts_fields([
                ("name", models.CharField(max_length=60)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True, validators=[MinValueValidator(1)])),
                ("is_active", models.BooleanField(default=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rooms", to="backend.branch")),
            ]),
            options={"ordering": ["branch", "name"], "unique_together": {("branch", "name")}},
        ),
        migrations.CreateModel(
            name="Shift",
            fields=ts_fields([
                ("name", models.CharField(max_length=50)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shifts", to="backend.branch")),
            ]),
            options={"ordering": ["branch", "start_time"], "unique_together": {("branch", "name")}},
        ),
        migrations.CreateModel(
            name="SchoolMembership",
            fields=ts_fields([
                ("is_active", models.BooleanField(default=True)),
                ("primary_branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="primary_memberships", to="backend.branch")),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="backend.school")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="school_memberships", to=settings.AUTH_USER_MODEL)),
            ]),
            options={"unique_together": {("user", "school")}},
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=ts_fields([
                ("employee_number", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("on_leave", "On leave"), ("inactive", "Inactive"), ("terminated", "Terminated")], default="active", max_length=20)),
                ("primary_branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="teachers", to="backend.branch")),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="teachers", to="backend.school")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="teacher_profiles", to=settings.AUTH_USER_MODEL)),
            ]),
            options={"ordering": ["school", "employee_number"], "unique_together": {("school", "employee_number")}},
        ),
        migrations.CreateModel(
            name="Staff",
            fields=ts_fields([
                ("employee_number", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("position", models.CharField(max_length=100)),
                ("national_id", models.CharField(blank=True, max_length=50)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("on_leave", "On leave"), ("inactive", "Inactive"), ("terminated", "Terminated")], default="active", max_length=20)),
                ("primary_branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="staff", to="backend.branch")),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="staff", to="backend.school")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="staff_profiles", to=settings.AUTH_USER_MODEL)),
            ]),
            options={"ordering": ["school", "employee_number"], "unique_together": {("school", "employee_number")}},
        ),
        migrations.CreateModel(
            name="MembershipRole",
            fields=ts_fields([
                ("role", models.CharField(choices=[("owner", "Owner"), ("admin", "Administrator"), ("manager", "Manager"), ("teacher", "Teacher"), ("staff", "Staff"), ("guardian", "Guardian"), ("student", "Student")], max_length=20)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="role_assignments", to="backend.branch")),
                ("membership", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="roles", to="backend.schoolmembership")),
            ]),
            options={"unique_together": {("membership", "role", "branch")}},
        ),
        migrations.CreateModel(
            name="StudentGuardian",
            fields=ts_fields([
                ("relationship", models.CharField(max_length=40)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_emergency_contact", models.BooleanField(default=False)),
                ("guardian", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="student_links", to="backend.guardian")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="guardian_links", to="backend.student")),
            ]),
            options={"unique_together": {("student", "guardian")}},
        ),
        migrations.CreateModel(
            name="Section",
            fields=ts_fields([
                ("name", models.CharField(max_length=40)),
                ("max_capacity", models.PositiveIntegerField(blank=True, null=True, validators=[MinValueValidator(1)])),
                ("is_active", models.BooleanField(default=True)),
                ("academic_year", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="backend.academicyear")),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="backend.branch")),
                ("grade_level", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sections", to="backend.gradelevel")),
                ("homeroom_teacher", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="homeroom_sections", to="backend.teacher")),
                ("room", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sections", to="backend.room")),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="backend.school")),
                ("shift", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sections", to="backend.shift")),
            ]),
            options={"ordering": ["academic_year", "grade_level", "name"], "unique_together": {("branch", "academic_year", "grade_level", "name")}},
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=ts_fields([
                ("status", models.CharField(choices=[("active", "Active"), ("transferred", "Transferred"), ("withdrawn", "Withdrawn"), ("completed", "Completed")], default="active", max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("roll_number", models.CharField(blank=True, max_length=30)),
                ("section", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="enrollments", to="backend.section")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to="backend.student")),
            ]),
            options={"ordering": ["-created_at"], "unique_together": {("student", "section", "start_date")}},
        ),
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=ts_fields([
                ("is_active", models.BooleanField(default=True)),
                ("section", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="teaching_assignments", to="backend.section")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_assignments", to="backend.subject")),
                ("teacher", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_assignments", to="backend.teacher")),
                ("term", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_assignments", to="backend.term")),
            ]),
            options={"unique_together": {("section", "subject", "teacher", "term")}},
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=ts_fields([
                ("day_of_week", models.PositiveSmallIntegerField(choices=[(1, "Saturday"), (2, "Sunday"), (3, "Monday"), (4, "Tuesday"), (5, "Wednesday"), (6, "Thursday"), (7, "Friday")])),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("assignment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="schedule_entries", to="backend.teachingassignment")),
                ("room", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="schedule_entries", to="backend.room")),
            ]),
            options={"ordering": ["day_of_week", "start_time"], "unique_together": {("assignment", "day_of_week", "start_time", "end_time")}},
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=ts_fields([
                ("date", models.DateField()),
                ("status", models.CharField(choices=[("present", "Present"), ("absent", "Absent"), ("late", "Late"), ("excused", "Excused")], max_length=20)),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                ("source", models.CharField(choices=[("manual", "Manual"), ("fingerprint", "Fingerprint"), ("device", "Other device"), ("import", "Import")], default="manual", max_length=20)),
                ("remarks", models.CharField(blank=True, max_length=300)),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendance_records", to="backend.enrollment")),
                ("recorded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="attendance_recordings", to=settings.AUTH_USER_MODEL)),
            ]),
            options={"ordering": ["-date", "enrollment"], "unique_together": {("enrollment", "date")}},
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=ts_fields([
                ("name", models.CharField(max_length=120)),
                ("assessment_type", models.CharField(choices=[("quiz", "Quiz"), ("assignment", "Assignment"), ("midterm", "Midterm"), ("final", "Final"), ("other", "Other")], max_length=20)),
                ("date", models.DateField()),
                ("max_score", models.DecimalField(decimal_places=2, max_digits=7, validators=[MinValueValidator(Decimal("0.01"))])),
                ("pass_score", models.DecimalField(decimal_places=2, max_digits=7, validators=[MinValueValidator(Decimal("0.00"))])),
                ("weight_percent", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5, validators=[MinValueValidator(Decimal("0.00")), MaxValueValidator(Decimal("100.00"))])),
                ("is_published", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("assignment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assessments", to="backend.teachingassignment")),
            ]),
            options={"ordering": ["-date", "name"], "unique_together": {("assignment", "name", "date")}},
        ),
        migrations.CreateModel(
            name="AssessmentResult",
            fields=ts_fields([
                ("score", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("status", models.CharField(choices=[("graded", "Graded"), ("absent", "Absent"), ("excused", "Excused"), ("not_graded", "Not graded")], default="not_graded", max_length=20)),
                ("remarks", models.CharField(blank=True, max_length=300)),
                ("assessment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="results", to="backend.assessment")),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assessment_results", to="backend.enrollment")),
                ("graded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="graded_results", to=settings.AUTH_USER_MODEL)),
            ]),
            options={"unique_together": {("assessment", "enrollment")}},
        ),
        migrations.CreateModel(
            name="FeeCharge",
            fields=ts_fields([
                ("category", models.CharField(max_length=60)),
                ("description", models.CharField(blank=True, max_length=250)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, validators=[MinValueValidator(Decimal("0.01"))])),
                ("discount_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12, validators=[MinValueValidator(Decimal("0.00"))])),
                ("currency", models.CharField(default="AFN", max_length=3)),
                ("due_date", models.DateField()),
                ("status", models.CharField(choices=[("unpaid", "Unpaid"), ("partial", "Partially paid"), ("paid", "Paid"), ("overdue", "Overdue"), ("waived", "Waived")], default="unpaid", max_length=20)),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fee_charges", to="backend.enrollment")),
            ]),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=ts_fields([
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, validators=[MinValueValidator(Decimal("0.01"))])),
                ("payment_date", models.DateField(default=django.utils.timezone.localdate)),
                ("payment_method", models.CharField(choices=[("cash", "Cash"), ("mobile_money", "Mobile money"), ("bank", "Bank"), ("other", "Other")], max_length=20)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("receipt_number", models.CharField(max_length=80, unique=True)),
                ("notes", models.CharField(blank=True, max_length=300)),
                ("fee_charge", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="backend.feecharge")),
                ("received_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="received_payments", to=settings.AUTH_USER_MODEL)),
            ]),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=ts_fields([
                ("title", models.CharField(max_length=150)),
                ("category", models.CharField(max_length=60)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, validators=[MinValueValidator(Decimal("0.01"))])),
                ("currency", models.CharField(default="AFN", max_length=3)),
                ("expense_date", models.DateField()),
                ("payment_method", models.CharField(blank=True, max_length=30)),
                ("payee", models.CharField(blank=True, max_length=120)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="expenses", to="backend.branch")),
                ("recorded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recorded_expenses", to=settings.AUTH_USER_MODEL)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="expenses", to="backend.school")),
            ]),
        ),
        migrations.CreateModel(
            name="PayrollEntry",
            fields=ts_fields([
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=12, validators=[MinValueValidator(Decimal("0.00"))])),
                ("bonus_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12, validators=[MinValueValidator(Decimal("0.00"))])),
                ("deduction_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12, validators=[MinValueValidator(Decimal("0.00"))])),
                ("status", models.CharField(choices=[("unpaid", "Unpaid"), ("paid", "Paid"), ("cancelled", "Cancelled")], default="unpaid", max_length=20)),
                ("paid_on", models.DateField(blank=True, null=True)),
                ("payment_method", models.CharField(blank=True, max_length=30)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_payroll", to=settings.AUTH_USER_MODEL)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payroll_entries", to="backend.school")),
                ("staff", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payroll_entries", to="backend.staff")),
                ("teacher", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payroll_entries", to="backend.teacher")),
            ]),
        ),
        migrations.CreateModel(
            name="Asset",
            fields=ts_fields([
                ("asset_code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=150)),
                ("category", models.CharField(max_length=60)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("purchase_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[MinValueValidator(Decimal("0.00"))])),
                ("quantity", models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])),
                ("condition", models.CharField(choices=[("new", "New"), ("good", "Good"), ("needs_repair", "Needs repair"), ("damaged", "Damaged")], default="good", max_length=20)),
                ("status", models.CharField(choices=[("active", "Active"), ("in_storage", "In storage"), ("disposed", "Disposed")], default="active", max_length=20)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("assigned_to", models.CharField(blank=True, max_length=120)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assets", to="backend.branch")),
            ]),
            options={"unique_together": {("branch", "asset_code")}},
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=ts_fields([
                ("title", models.CharField(max_length=150)),
                ("message", models.TextField()),
                ("audience", models.CharField(choices=[("all", "Everyone"), ("staff", "Staff"), ("teachers", "Teachers"), ("guardians", "Guardians"), ("students", "Students")], default="all", max_length=20)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="announcements", to="backend.branch")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="announcements_created", to=settings.AUTH_USER_MODEL)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="announcements", to="backend.school")),
            ]),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=ts_fields([
                ("title", models.CharField(max_length=150)),
                ("message", models.TextField()),
                ("notification_type", models.CharField(choices=[("general", "General"), ("announcement", "Announcement"), ("fee", "Fee"), ("attendance", "Attendance"), ("assessment", "Assessment")], default="general", max_length=20)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notifications_created", to=settings.AUTH_USER_MODEL)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="backend.school")),
            ]),
        ),
        migrations.CreateModel(
            name="NotificationRecipient",
            fields=ts_fields([
                ("channel", models.CharField(choices=[("in_app", "In app"), ("email", "Email"), ("sms", "SMS"), ("push", "Push")], default="in_app", max_length=20)),
                ("delivery_status", models.CharField(choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed")], default="pending", max_length=20)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("notification", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recipients", to="backend.notification")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notification_recipients", to=settings.AUTH_USER_MODEL)),
            ]),
            options={"unique_together": {("notification", "user", "channel")}},
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=120)),
                ("entity_type", models.CharField(max_length=80)),
                ("entity_id", models.CharField(blank=True, max_length=80)),
                ("details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activity_logs", to="backend.school")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="activity_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
